### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by saulshanabrook**
Add integration testing with [Cypress](https://www.cypress.io/). This makes sure we can open CSV and JSON files and voyager and that the windows stay open when we reload.

This runs the non-docker based testing in Travis. In the future, it would be good to run both docker and non docker in CI, so we can verify that both methods are working for development.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@ellisonbg @tkinz27 Do either of you wanna review this? Hopefully these last tests will pass on Travis.

**Comment by ellisonbg** [comment]
Cool, I don't know of work done to help us test extensions. I am fine with merging and iterating on this.

Ping @blink1073 @jasongrout @ian-r-rose to see if this would be useful more broadly.

**Comment by ian-r-rose** [comment]
@saulshanabrook Interesting, I have not looked at Cypress much. I run tests for `@jupyterlab/google-drive` in CI using karma, in case you are interested in looking at another approach to this problem.

**Comment by blink1073** [comment]
Cypress looks great, thanks for the ping!  Until they merge support for unit tests on their [roadmap](https://github.com/cypress-io/cypress/issues/318), I'd say it is not yet appropriate to replace our karma infrastructure, since Cypress does a lot of setup work between test items.  It is certainly a great replacement for Selenium.  We had currently only used [Selenium](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/selenium_check.py) to make sure the page loads and that no errors or warnings happen during app startup.

**Comment by saulshanabrook** [comment]
This was my first time using Cypress and I really enjoyed it. I created all the tests using `cypress open`, which let me easily re-run my tests when I changed a file and use the web inspector to understand what was going wrong.

I didn't add any unit tests here, because I am less familiar with the JupyterLab internals. It was easier for me to understand what the behavior should be than how any of it works under the covers.

@ian-r-rose I notice in [the `@jupyterlab/google-drive` CI setup](https://github.com/jupyterlab/jupyterlab-google-drive/blob/ae5accd1261a5c86a75f716141d9de55695202e5/.travis.yml#L14) that you install jupyterlab from the source. Is this just to make sure it's compatible with master?

**Comment by ian-r-rose** [comment]
@saulshanabrook, yes, it is a bit more complicated than it would be otherwise in order to test against JupyterLab master. Once development on that stabilizes I will probably switch to testing against released packages.

**Pull request merged**
