### PR TITLE
update to jupyterlab 0.31.5

### PR DESCRIPTION
**Pull request by zzhangjii**
1. works with jupyterlab 0.31.5
2. for local files, open through context menu "open with" and select "voyager (filetype)"
3. for data frame inside jupyter notebook(tables and graphs), open through context menu "open with voyager", then a json file containing the source data will be created locally and open a voyager page with the data

Note:
currently, there's some problem with newer datavoyager versions (v2.0.0-alpha.13, 14, 15), the graph won't load, so, it only uses older datavoyager version "v2.0.0-alpha.12"

### CODE REVIEW

**Comment by saulshanabrook** [comment]
It still fails to load for me with jupyterlab 0.31.5

screen shot 2018-02-15 at 3 13 14 pm

**Comment by zzhangjii** [comment]
I remember this was caused by some node_module version conflicts, but I can only solve it through re-installation.

_pip uninstall jupyterlab_
remember to delete the jupyter folder in python enviroment;
then
_pip install jupyterlab_

try use the most recent for 0.31.8:
_git clone git@github.com:zzhangjii/jupyterlab_voyager.git_

**Comment by saulshanabrook** [comment]
Since master is already broken, I am going to merge this so I can more easily iterate on top of it.

**Comment by saulshanabrook** [comment]
Woops, merged into wrong branch. Going to manually merge locally.

**Comment by saulshanabrook** [comment]
OK I did a little git branch cleanup. Your changes are now merged into master.

**Pull request merged**
