### PR TITLE
Upgrade to JupyterLab 0.32

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@zzhangjii Do you have a branch that you are working off of? If not, I am inclined to merge this and get our tests working again.

**Comment by zzhangjii** [comment]
@saulshanabrook  I created a new pull request to include recent updates, should I merge to master branch?

**Comment by saulshanabrook** [comment]
@gnestor Thanks for opening this. I am gonna cherry pick a few of your commits off, since I can't merge this now that I merged @zzhangjii's branch.

**Comment by gnestor** [comment]
Hey guys, I just rebased. It looks like "fix typescript build" and "add binder support" are in master already. This adds jupyterlab 0..32 support, fixes a pesky error message, and cleans up the formatting.

**Comment by saulshanabrook** [comment]
@gnestor Thank you!

**Pull request merged**
